### ISSUE TITLE
Testing for STDIN

### ISSUE THREAD

**Issue by tlawrence3** [tlawrence3/FAST#28]
We currently use a version of these two statements to check if data is being piped in or from a file:

```
pod2usage("$NAME: Requires at least one argument FILE.\n") if ((-t STDIN) && (@ARGV == 0));
pod2usage("$NAME: zero if input is from STDIN.\n") if (!(-t STDIN) && (@ARGV != 0));
```

This works fine when the utility is called interactively from the shell. For example these work as expected:

```
faswc -qs fasta_file.fq
cat fasta_file.fq | faswc -qs
```

However, when the utility is called from a bash script or something like org-mode in emacs the script thinks it is having data being piped in and throws the pod2usage error when files are given as arguments. Here is an example that causes this behavior:

```
#!/bin/bash
while read line
do
faswc -qs $line  >> output_file
done < file_names.txt
```

I am guessing that this is happening because -t STDIN is returning false because it is being run non-interactively so it is not attached to a terminal.

**Comment by dhard** [comment]
Again, Brian D Foy may provide the fix for this with IO::Interactive

http://search.cpan.org/dist/IO-Interactive/lib/IO/Interactive.pm
