### ISSUE TITLE
Use /usr/bin/env for hash-bang lines

### ISSUE THREAD

**Issue by tseemann** [tlawrence3/FAST#30]
I notice your scripts begin with ```#!/usr/bin/perl -wT```

Could you change them to be ```#!/usr/bin/env perl``` ?

This will ensure the correct Perl is used, as many of us have custom Perl in other locations that are in the PATH before the system Perl.

The ```-w``` for warnings is deprecated. Add ```use warnings;``` instead.

I'm not sure about taint mode ```-T```. You can't use command line switches when using the ```env`` method of running Perl! Might be info here: http://perldoc.perl.org/perlsec.html

**Comment by dhard** [comment]
Hi Torsten, thanks for the feedback. 
Yes, we'll fix this in the next release.

> On Jun 5, 2015, at 8:02 PM, Torsten Seemann <notifications@github.com> wrote:
> 
> I notice your scripts begin with #!/usr/bin/perl -wT
> 
> Could you change them to be #!/usr/bin/env perl ?
> 
> This will ensure the correct Perl is used, as many of us have custom Perl in other locations that are in the PATH before the system Perl.
> 
> The -w for warnings is deprecated. Add use warnings; instead.
> 
> I'm not sure about taint mode -T. You can't use command line switches when using the `env method of running Perl! Might be info here: http://perldoc.perl.org/perlsec.html
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
David H. Ardell
Assistant Professor, Molecular Cell Biology Unit
Chair, Quantitative and Systems Biology Program
5200 North Lake Road, School of Natural Sciences, University of California, Merced CA 95343
office: SE 228 // (209) 228-2953 // fax: (209) 228-4675 // http://compbio.ucmerced.edu/ardell
OFFICE HOURS FOR BIO 2 and QSB: Tuesdays and Thursdays, 1:30 pm to 2:30 pm or by appt.

**Comment by tlawrence3** [comment]
shebang lines have been updated.
