### ISSUE TITLE
How do I list all the tools included in FAST ?

### ISSUE THREAD

**Issue by tseemann** [tlawrence3/FAST#31]
Besides typing {fas,gb,aln} and pressing <tab> is there any way I can find out all the tools available?

I think it needs something like ```wossname``` or ```tfm``` in the EMBOSS package.

Maybe the simplest thing would be 
* a man page for "fast" 
* running "fast"

Both of these would list each tool and short description (the man NAME line?), one per line:
```
% fast
FASTA
faswc - tally sequences and characters
fasuniq - Remove duplicate sequence records in a multifasta file or datastream.
fastail
...
GENBANK
gbfalncut
gbfcut
...
ALIGNMENT
alnpi
alncut
...

**Comment by dhard** [comment]
We have this already written ("man fast" lists all the executables) so we'll make sure it gets installed in the next release.

> On Jun 5, 2015, at 8:08 PM, Torsten Seemann <notifications@github.com> wrote:
> 
> Besides typing {fas,gb,aln} and pressing is there any way I can find out all the tools available?
> 
> I think it needs something like wossname or tfm in the EMBOSS package.
> 
> Maybe the simplest thing would be
> 
> 	• a man page for "fast"
> 	• running "fast" Both of these would list each tool and short description (the man NAME line?), one per line:
> % fast
> FASTA
> faswc - tally sequences and characters
> fasuniq - Remove duplicate sequence records in a multifasta file or datastream.
> fastail
> ...
> GENBANK
> gbfalncut
> gbfcut
> ...
> ALIGNMENT
> alnpi
> alncut
> ...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
David H. Ardell
Assistant Professor, Molecular Cell Biology Unit
Chair, Quantitative and Systems Biology Program
5200 North Lake Road, School of Natural Sciences, University of California, Merced CA 95343
office: SE 228 // (209) 228-2953 // fax: (209) 228-4675 // http://compbio.ucmerced.edu/ardell
OFFICE HOURS FOR BIO 2 and QSB: Tuesdays and Thursdays, 1:30 pm to 2:30 pm or by appt.

**Comment by tseemann** [comment]
A command as well would be good so you can "fast | grep dup" for example.

**Comment by dhard** [comment]
Yes. This is already written. I'm fixing this in a new release, I will try to release this coming week.

Dave

> On Jun 13, 2015, at 4:35 PM, Torsten Seemann <notifications@github.com> wrote:
> 
> A command as well would be good so you can "fast | grep dup" for example.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
David H. Ardell
Assistant Professor, Molecular Cell Biology Unit
Chair, Quantitative and Systems Biology Program
5200 North Lake Road, School of Natural Sciences, University of California, Merced CA 95343
office: SE 228 // (209) 228-2953 // fax: (209) 228-4675 // http://compbio.ucmerced.edu/ardell
OFFICE HOURS FOR BIO 2 and QSB: Tuesdays and Thursdays, 1:30 pm to 2:30 pm or by appt.

**Comment by tseemann** [comment]
Thanks Dave.
