### ISSUE TITLE
Taint mode prevents FAST installation in user folders

### ISSUE THREAD

**Issue by mfasold** [tlawrence3/FAST#36]
It seems as there is no easy way to use FAST on a server without admin access. FAST requires a fair amount of dependencies to be installed (which I personally think is not in line with the UNIX philosophy). But if one needs to install those into a user directory, one needs to change include folders via PERL5LIB environment variable. This however is ignored in taint mode.

**Comment by tlawrence3** [comment]
Sorry about the taint mode issue. I just pushed a commit that removes taint mode from all the utilities, which we have been meaning to do. We attempted to keep dependencies to a minimum and currently FAST requires Pod::Usage (produces man pages), Sort::Key, Sort::MergeSort (both used by fassort), and Bit::Vector (alncut). 

The best solution I have found for installing on my university's cluster, where I don't have admin access, is by using [perlbrew](https://perlbrew.pl/). This also gives you the advantage of having access to any perl version you want all with their own package repositories. If you need any additional help installing open another issue.
