### ISSUE TITLE
`faswc` gives incorrect counts

### ISSUE THREAD

**Issue by arendsee** [tlawrence3/FAST#64]
Given the FASTA file:

```
$ cat test.faa
>a
M
>b
MM
>c
MMMM
>d
MMMMMMMM
```
I get the following result:

```
$ faswc test.faa
     2              5 test.faa
     2              5 total
```

`faswc` appears to only be considering every other entry. Perhaps it is getting mixed up between FASTA and FASTQ format?

**Comment by tlawrence3** [comment]
Thank you for catching this. Are you using the most recent commit? I will look into this when after the lab I am TAing is over and should have a fix pushed by the end of the day.

**Comment by arendsee** [comment]
I am using the most recent commit from the master branch (I installed from source)

**Comment by tlawrence3** [comment]
I tested this commit on fasta and fastq files and it seems to be working correctly. You no longer need to indicate if you are using a fastq file and parsing should be ~10-20X faster for fastq files. We will be implementing a test suite soon to hopefully catch these kinds of errors before pushing them. Thanks again @arendsee for catching this error and taking the time to report it.

**Comment by arendsee** [comment]
No problem. I have a little FASTA program of my own, [smof](https://github.com/arendsee/smof) that is pretty similar to `FAST`, if you are interested in taking a look. I've just been drafting a comparison of the two (in the README).

**Comment by tlawrence3** [comment]
smof looks like a nice set of utilities. We do have significant overlap in functionality along with useful unique utilities. It is great that our tools are interoperable with so we can take advantage of unique features in both.

Currently, our goals are speeding up the FAST utilities within the limits of Perl. We are replacing most of the bioperl code, which has provided a 2X speed increase on fasta files and ~10-20X speed increase on fastq files.

**Comment by arendsee** [comment]
That should make the speed comparable to `smof`. You could also add support for indexed FASTA files.
